/* 
헤더 풋터 등의 레이아웃을 작업하는 컴포넌트
*/
"use client"

import "./globals.css"
import Nav from "./components/Nav";
import Footer from "./components/Footer";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({children,}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>
      <Nav/>
        {children}
        </body>
      <Footer/>
    </html>
  )
}

// styled components

